name: algohive
services:
  server:
    container_name: algohive-server
    image: ghcr.io/algohive-coding-puzzles/api:latest
    env_file: server.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - algohive-network

  # client:
  #   image: ghcr.io/eric-philippe/algohive/algohive/client:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - algohive-network

  beehub:
    container_name: beehub
    image: ghcr.io/algohive-coding-puzzles/beehub:latest
    ports:
      - "8081:8081"
    networks:
      - algohive-network
    environment:
      - DISCOVERY_PORT_RANGE_START=5000
      - DISCOVERY_PORT_RANGE_END=5099
      - DISCOVERY_ENABLED=true
      - DISCOVERY_SERVICE_TYPE=beeapi

  beeapi-server1:
    container_name: beeapi-server-tlse
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - ./data/beeapi-server1/puzzles:/app/puzzles
    ports:
      - "5000:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Toulouse
      - SERVER_DESCRIPTION=This is the server containing puzzles for all the students at Ynov Toulouse
    labels:
      - "algohive.service.type=beeapi"

  beeapi-server2:
    container_name: beeapi-server-mpl
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - ./data/beeapi-server2/puzzles:/app/puzzles
    ports:
      - "5001:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Montpellier
      - SERVER_DESCRIPTION=This is the server containing puzzles for all the students at Ynov Montpellier
    labels:
      - "algohive.service.type=beeapi"

  db:
    container_name: algohive-db
    image: postgres:17-alpine
    restart: unless-stopped
    env_file: server.env
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - algohive-network

  cache:
    container_name: algohive-cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - algohive-network

volumes:
  db-data:

networks:
  algohive-network:
