name: algohive
services:
  server:
    container_name: algohive-server
    image: ghcr.io/algohive-coding-puzzles/api:latest
    env_file: server.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    ports:
      - "8001:8080"
    networks:
      - algohive-network

  client:
    container_name: algohive-client
    image: docker pull ghcr.io/algohive-coding-puzzles/client:latest
    restart: unless-stopped
    ports:
      - "7002:8000"
    networks:
      - algohive-network

  beehub:
    container_name: beehub
    image: ghcr.io/algohive-coding-puzzles/beehub:latest
    ports:
      - "8002:8081"
    networks:
      - algohive-network
    env_file: server.env

  beeapi-server1:
    container_name: beeapi-server-tlse
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - ./data/beeapi-server1/puzzles:/app/puzzles
    ports:
      - "5000:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Toulouse
      - SERVER_DESCRIPTION=This is the server containing puzzles for all the students at Ynov Toulouse
    labels:
      - "algohive.service.type=beeapi"

  beeapi-server2:
    container_name: beeapi-server-mpl
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - ./data/beeapi-server2/puzzles:/app/puzzles
    ports:
      - "5001:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Montpellier
      - SERVER_DESCRIPTION=This is the server containing puzzles for all the students at Ynov Montpellier
    labels:
      - "algohive.service.type=beeapi"

  beeapi-server-staging:
    container_name: beeapi-server-staging
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - ./data/beeapi-server/puzzles:/app/puzzles
    ports:
      - "5003:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Montpellier-Staging
      - SERVER_DESCRIPTION=This is the sandbox staging server for M1 students to create puzzles.
    labels:
      - "algohive.service.type=beeapi"

  algohive-db:
    container_name: algohive-db
    image: postgres:17-alpine
    restart: unless-stopped
    env_file: server.env
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - algohive-network

  algohive-cache:
    container_name: algohive-cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - algohive-network

volumes:
  db-data:

networks:
  algohive-network:
