name: algohive
services:
  algohive-server:
    container_name: algohive-server
    image: ghcr.io/algohive-coding-puzzles/api:latest
    env_file: server.env
    depends_on:
      - algohive-db
      - algohive-cache
    restart: unless-stopped
    ports:
      - "8001:8080"
    networks:
      - algohive-network

  algohive-client:
    container_name: algohive-client
    image: ghcr.io/algohive-coding-puzzles/client:latest
    restart: unless-stopped
    ports:
      - "7002:80"
    networks:
      - algohive-network

  beehub:
    container_name: beehub
    image: ghcr.io/algohive-coding-puzzles/beehub:latest
    ports:
      - "8002:8081"
    networks:
      - algohive-network
    env_file: server.env
    volumes:
      - beehub-db:/app/backend/db
    depends_on:
      - beeapi-server-tlse
      - beeapi-server-mpl
      - beeapi-server-staging

  beeapi-server-tlse:
    container_name: beeapi-server-tlse
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - puzzles-tlse:/app/puzzles
    ports:
      - "5000:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Toulouse
      - SERVER_DESCRIPTION=This is the server containing puzzles for all the students at Ynov Toulouse
    labels:
      - "algohive.service.type=beeapi"

  beeapi-server-mpl:
    container_name: beeapi-server-mpl
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - puzzles-mpl:/app/puzzles
    ports:
      - "5001:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Montpellier
      - SERVER_DESCRIPTION=This is the server containing puzzles for all the students at Ynov Montpellier
    labels:
      - "algohive.service.type=beeapi"

  beeapi-server-staging:
    container_name: beeapi-server-staging
    image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
    restart: unless-stopped
    volumes:
      - puzzles-staging:/app/puzzles
    ports:
      - "5002:5000"
    networks:
      - algohive-network
    environment:
      - SERVER_NAME=Ynov-Montpellier-Staging
      - SERVER_DESCRIPTION=This is the sandbox staging server for M1 students to create puzzles.
    labels:
      - "algohive.service.type=beeapi"

  algohive-db:
    container_name: algohive-db
    image: postgres:17-alpine
    restart: unless-stopped
    env_file: server.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - algohive-network

  algohive-cache:
    container_name: algohive-cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - algohive-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    networks:
      - algohive-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - algohive-network
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  db-data:
  puzzles-tlse:
  puzzles-mpl:
  puzzles-staging:
  beehub-db:
  grafana_data:
  prometheus_data:

networks:
  algohive-network:
