global:
  scrape_interval: 15s
  evaluation_interval: 15s
  retention.time: 5d

scrape_configs:
  - job_name: "algohive-api"
    metrics_path: "/api/v1/metrics"
    static_configs:
      - targets: ["algohive-server:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
